### ISSUE TITLE
options.ignore removes .classname but keeps @keyframes classname?

### ISSUE THREAD

**Issue by t1mmen** [addyosmani/grunt-uncss#114]
Hi,

Using `options.ignore = ['slideInLeft']` in my `Gruntfile.js`, it appears to preserve the @keyframes name, but remove the classname if both are identical (as they are in animate.css)

Relevant output without uncss:

``` css
@keyframes slideInLeft {
  0% {
    opacity: 0;
    -webkit-transform: translateX(-2000px);
    -ms-transform: translateX(-2000px);
    transform: translateX(-2000px);
  }
  100% {
    -webkit-transform: translateX(0);
    -ms-transform: translateX(0);
    transform: translateX(0);
  }
}
.slideInLeft {
  -webkit-animation-name: slideInLeft;
  animation-name: slideInLeft;
}
```

Output using uncss:

``` css
@keyframes slideInLeft {
  0% {
    opacity: 0;
    -webkit-transform: translateX(-2000px);
    -ms-transform: translateX(-2000px);
    transform: translateX(-2000px);
  }
  100% {
    -webkit-transform: translateX(0);
    -ms-transform: translateX(0);
    transform: translateX(0);
  }
}
/* missing .sideInLeft! */
```

Since `.slideInLeft` is added via JS on my page, I also tried including the classname in the static HTML, with the same result.

I'm using Grunt v0.4.2 & uncss 0.3.5.

Let me know if this should be reported upstream instead.

PS: Thank you so much for your work, not only on grunt-uncss, but all the other wonderful projects you've contributed to that I use :)
