### ISSUE TITLE
Implement support for detection of duplication across media queries

### ISSUE THREAD

**Issue by jrcryer** [addyosmani/grunt-uncss#3]
This would be a nice feature to detect duplication across media queries.  For example:

``` css
#header {
   color: #000;
   font-size: 1em;
}

@media screen and (min-width:320px) {
    #header {
        color: #000;
        font-size: 2.4em;
    }
}
```

The color property would be flagged as duplicated.
